
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

/**
 * Exports a given HTML element as a multi-page PDF with loading UI.
 *
 * @param {HTMLElement} element - The DOM element to export.
 * @param {string} title - PDF file name and header title.
 * @param {Function} setLoading - React state setter: setLoading(true/false)
 */
export const exportBlogToPDF = async (element, title = "AI Blog", setLoading) => {
  if (!element) {
    alert("No content found to export!");
    return;
  }

  // --- Start loading ---
  setLoading?.(true);

  try {
    // 1. Capture the blog
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      scrollY: -window.scrollY, // fix scroll offset
      windowWidth: document.documentElement.offsetWidth,
      windowHeight: document.documentElement.offsetHeight,
      logging: false,
    });

    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    let heightLeft = pdfHeight;
    let position = 0;

    // Add first page
    pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);
    heightLeft -= pdf.internal.pageSize.getHeight();

    // Add extra pages
    while (heightLeft > 0) {
      position = heightLeft - pdfHeight;
      pdf.addPage();
      pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);
      heightLeft -= pdf.internal.pageSize.getHeight();
    }

    // Header
    pdf.setFontSize(16);
    pdf.setTextColor(40);
    pdf.text(title, 15, 15);

    // Footer on every page
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(10);
      pdf.setTextColor(150);
      pdf.text(
        `Generated by AI Blog Generator — Page ${i}/${totalPages}`,
        15,
        pdf.internal.pageSize.getHeight() - 10
      );
    }

    // Save
    pdf.save(`${title.replace(/[^a-z0-9]/gi, "_")}.pdf`);
  } catch (error) {
    console.error("PDF export failed:", error);
    alert("Failed to generate PDF. Please try again.");
  } finally {
    // --- End loading ---
    setLoading?.(false);
  }
};